spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_student
    username: root
    password: 123456
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      filters: stat,wall
      filter:
        stat:
          slow-sql-millis: 1000
          enabled: true
        wall:
          enabled: true

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      aop-patterns: com.huanglong.admin.*


#mybatis:
#  mapper-locations: classpath:mapper/*.xml


